# -*- mode: ruby -*-
# vi: set ft=ruby :

# Default VM Configs
$vm_memory      = "384"
$vm_cpus        = "1"
$vm_http_port   = 80
$host_http_port = 8080

Vagrant.configure("2") do |config|
  config.vm.box = "stubbornella"

  # === box URLS ===
  config.vm.box_url = "https://dl.dropbox.com/u/558452/vagrant/package.box"
  #config.vm.box_url = "~/Dropbox/Public/vagrant/package.box"

  # === box config ===
  config.vm.network :forwarded_port, guest: $vm_http_port, host: $host_http_port
  #config.vm.synced_folder ".", "/vagrant"
  #vb.gui = true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", $vm_memory]
    vb.customize ["modifyvm", :id, "--cpus",   $vm_cpus]
  end

  # provision only if .vagrantstartt exists
  #if File.exist?(".vagrantstart")
  #  config.vm.provision :shell, :path => ".vagrantstart"
  #end

  config.vm.provision :shell, :path => "tools/vagrant/vagrant_user.sh"
end

